entrada = input('digite algo: ')
print('O tipo primitivo é: ', type(entrada))
print('So tem espaço: ', entrada.isspace())
print('é um numero: ', entrada.isnumeric())
print('é alfabetico: ', entrada.isalpha())
print('é alfanumerico: ', entrada.isalnum())
print('esta em maisculas: ', entrada.isupper())
print('esta em minusculas: ', entrada.islower())
print('esta capitalizada: ', entrada.istitle())
