t = int(input('Digite um numero: '))

print('='*20)
print('{} X 1 = '.format(t,), t*1)
print('{} X 1 = '.format(t,), t*2)
print('{} X 1 = '.format(t,), t*3)
print('{} X 1 = '.format(t,), t*4)
print('{} X 1 = '.format(t,), t*5)
print('{} X 1 = '.format(t,), t*6)
print('{} X 1 = '.format(t,), t*7)
print('{} X 1 = '.format(t,), t*8)
print('{} X 1 = '.format(t,), t*9)
print('{} X 1 = '.format(t,), t*10)
print('='*20)